baseurl: "/quick-switcher"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

sass:
  sass_dir: .

exclude:
  - build.js
  - Gemfile
  - Gemfile.lock
  - LICENSE*
  - Makefile
  - node_modules
  - package.json
  - README.md
  - vendor
  - yarn.lock
